name: build

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
