name: build

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
        cache: maven
    - name: Build with Gradle
      run: ./gradlew build
